[package]
name = "agoradb-query"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agoradb-core = { path = "../agoradb-core" }
agoradb-catalog = { path = "../agoradb-catalog" }
thiserror = { workspace = true }
datafusion = { workspace = true }
sqlparser = "0.59"

[dev-dependencies]
