[package]
name = "agoradb-query"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agoradb-core = { path = "../agoradb-core" }
agoradb-catalog = { path = "../agoradb-catalog" }
thiserror = { workspace = true }
datafusion = { workspace = true }
sqlparser = "0.59"
iceberg = "0.9"

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"
iceberg = "0.9"
agoradb-storage = { path = "../agoradb-storage" }
arrow-array = "57"
arrow-schema = "57"
