[package]
name = "agoradb-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
agoradb-catalog = { path = "../crates/agoradb-catalog" }
agoradb-core = { path = "../crates/agoradb-core" }
agoradb-query = { path = "../crates/agoradb-query" }
iceberg = "0.9"
tokio = { workspace = true }
