[package]
name = "agoradb-physical"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agoradb-core = { path = "../agoradb-core" }
agoradb-execution = { path = "../agoradb-execution" }
agoradb-logical = { path = "../agoradb-logical" }
thiserror = { workspace = true }
