[package]
name = "agoradb-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
agoradb-core = { path = "../agoradb-core" }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
iceberg = { workspace = true }
parquet = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio-test = { workspace = true }
agoradb-catalog = { path = "../agoradb-catalog" }
